service: workout-server

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  environment:
    USER_TABLE: ${self:service}-${opt:stage, self:provider.stage}-user
    EXERCISE_TABLE: ${self:service}-${opt:stage, self:provider.stage}-exercise
    USER_EXERCISE_TABLE: ${self:service}-${opt:stage, self:provider.stage}-user-exercise
    WORKOUT_TABLE: ${self:service}-${opt:stage, self:provider.stage}-workout
    USER_WORKOUT_TABLE: ${self:service}-${opt:stage, self:provider.stage}-user-workout
    WORKOUT_LOG_TABLE: ${self:service}-${opt:stage, self:provider.stage}-workout-log
    USER_STATS_TABLE: ${self:service}-${opt:stage, self:provider.stage}-user-stats
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}-${opt:stage, self:provider.stage}-*'
    - Effect: Allow
      Action:
        - s3:AbortMultipartUpload
        - s3:GetBucketLocation
        - s3:GetObject
        - s3:ListBucket
        - s3:ListBucketMultipartUploads
        - s3:PutObject
      Resource: '*'

functions:
  saveNewUser:
    handler: src/user_handlers.saveNewUser
    events:
      - http:
          path: saveNewUser
          method: post
          cors: true
  checkUser:
    handler: src/user_handlers.checkUser
    events:
      - http:
          path: checkUser
          method: post
          cors: true
  saveUser:
    handler: src/user_handlers.saveUser
    events:
      - http:
          path: saveUser
          method: post
          cors: true
  getUser:
    handler: src/user_handlers.getUser
    events:
      - http:
          path: getUser
          method: post
          cors: true
  updateUserImage:
    handler: src/user_handlers.updateUserImage
    events:
      - http:
          path: updateUserImage
          method: post
          cors: true
  saveExercise:
    handler: src/exercise_handlers.saveExercise
    events:
      - http:
          path: saveExercise
          method: post
          cors: true
  getExercisesForUser:
    handler: src/exercise_handlers.getExercisesForUser
    events:
      - http:
          path: getExercisesForUser
          method: post
          cors: true
  getExercises:
    handler: src/exercise_handlers.getExercises
    events:
      - http:
          path: getExercises
          method: post
          cors: true
  getAllExercises:
    handler: src/exercise_handlers.getAllExercises
    events:
      - http:
          path: getAllExercises
          method: get
          cors: true
  saveWorkout:
    handler: src/workout_handlers.saveWorkout
    events:
      - http:
          path: saveWorkout
          method: post
          cors: true
  getWorkouts:
    handler: src/workout_handlers.getWorkouts
    events:
      - http:
          path: getWorkouts
          method: post
          cors: true
  getWorkoutsForUser:
    handler: src/workout_handlers.getWorkoutsForUser
    events:
      - http:
          path: getWorkoutsForUser
          method: post
          cors: true
  saveCompletedWorkout:
    handler: src/workoutLog_handlers.saveCompletedWorkout
    events:
      - http:
          path: saveCompletedWorkout
          method: post
          cors: true
  getWorkoutLogForUser:
    handler: src/workoutLog_handlers.getWorkoutLogForUser
    events:
      - http:
          path: getWorkoutLogForUser
          method: post
          cors: true
  saveStatsForUser:
    handler: src/stats_handlers.saveStatsForUser
    events:
      - http:
          path: saveStatsForUser
          method: post
          cors: true
  getStatsForUser:
    handler: src/stats_handlers.getStatsForUser
    events:
      - http:
          path: getStatsForUser
          method: post
          cors: true
  getCompletedWorkoutsAndStatsForUser:
    handler: src/stats_handlers.getCompletedWorkoutsAndStatsForUser
    events:
      - http:
          path: getCompletedWorkoutsAndStatsForUser
          method: post
          cors: true

resources:
  Resources:
    UserTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25
        TableName: ${self:provider.environment.USER_TABLE}

    ExerciseTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25
        TableName: ${self:provider.environment.EXERCISE_TABLE}

    UserExerciseTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25
        TableName: ${self:provider.environment.USER_EXERCISE_TABLE}

    WorkoutTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25
        TableName: ${self:provider.environment.WORKOUT_TABLE}

    UserWorkoutTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25
        TableName: ${self:provider.environment.USER_WORKOUT_TABLE}

    WorkoutLogTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: wlId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: wlId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25
        TableName: ${self:provider.environment.WORKOUT_LOG_TABLE}

    UserStatsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25
        TableName: ${self:provider.environment.USER_STATS_TABLE}

plugins:
  - serverless-plugin-typescript
